package com.brickpi.java;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class brickpi implements brickpiConstants {
  public static void setSpi_file_handle(int value) {
    brickpiJNI.spi_file_handle_set(value);
  }

  public static int getSpi_file_handle() {
    return brickpiJNI.spi_file_handle_get();
  }

  public static void setSpi_xfer_struct(SWIGTYPE_p_spi_ioc_transfer value) {
    brickpiJNI.spi_xfer_struct_set(SWIGTYPE_p_spi_ioc_transfer.getCPtr(value));
  }

  public static SWIGTYPE_p_spi_ioc_transfer getSpi_xfer_struct() {
    return new SWIGTYPE_p_spi_ioc_transfer(brickpiJNI.spi_xfer_struct_get(), true);
  }

  public static void setSpi_array_out(SWIGTYPE_p_uint8_t value) {
    brickpiJNI.spi_array_out_set(SWIGTYPE_p_uint8_t.getCPtr(value));
  }

  public static SWIGTYPE_p_uint8_t getSpi_array_out() {
    long cPtr = brickpiJNI.spi_array_out_get();
    return (cPtr == 0) ? null : new SWIGTYPE_p_uint8_t(cPtr, false);
  }

  public static void setSpi_array_in(SWIGTYPE_p_uint8_t value) {
    brickpiJNI.spi_array_in_set(SWIGTYPE_p_uint8_t.getCPtr(value));
  }

  public static SWIGTYPE_p_uint8_t getSpi_array_in() {
    long cPtr = brickpiJNI.spi_array_in_get();
    return (cPtr == 0) ? null : new SWIGTYPE_p_uint8_t(cPtr, false);
  }

  public static int spi_setup() {
    return brickpiJNI.spi_setup();
  }

  public static int spi_transfer_array(SWIGTYPE_p_uint8_t length, SWIGTYPE_p_uint8_t outArray, SWIGTYPE_p_uint8_t inArray) {
    return brickpiJNI.spi_transfer_array(SWIGTYPE_p_uint8_t.getCPtr(length), SWIGTYPE_p_uint8_t.getCPtr(outArray), SWIGTYPE_p_uint8_t.getCPtr(inArray));
  }

  public static void fatal_error(String error) {
    brickpiJNI.fatal_error__SWIG_0(error);
  }

  public static int BrickPi3_set_address(int addr, String id) {
    return brickpiJNI.BrickPi3_set_address(addr, id);
  }

}
