package com.brickpi.java;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class i2c_struct_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected i2c_struct_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(i2c_struct_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        brickpiJNI.delete_i2c_struct_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSpeed(SWIGTYPE_p_uint8_t value) {
    brickpiJNI.i2c_struct_t_speed_set(swigCPtr, this, SWIGTYPE_p_uint8_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint8_t getSpeed() {
    return new SWIGTYPE_p_uint8_t(brickpiJNI.i2c_struct_t_speed_get(swigCPtr, this), true);
  }

  public void setDelay(SWIGTYPE_p_uint8_t value) {
    brickpiJNI.i2c_struct_t_delay_set(swigCPtr, this, SWIGTYPE_p_uint8_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint8_t getDelay() {
    return new SWIGTYPE_p_uint8_t(brickpiJNI.i2c_struct_t_delay_get(swigCPtr, this), true);
  }

  public void setAddress(SWIGTYPE_p_uint8_t value) {
    brickpiJNI.i2c_struct_t_address_set(swigCPtr, this, SWIGTYPE_p_uint8_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint8_t getAddress() {
    return new SWIGTYPE_p_uint8_t(brickpiJNI.i2c_struct_t_address_get(swigCPtr, this), true);
  }

  public void setLength_write(SWIGTYPE_p_uint8_t value) {
    brickpiJNI.i2c_struct_t_length_write_set(swigCPtr, this, SWIGTYPE_p_uint8_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint8_t getLength_write() {
    return new SWIGTYPE_p_uint8_t(brickpiJNI.i2c_struct_t_length_write_get(swigCPtr, this), true);
  }

  public void setBuffer_write(SWIGTYPE_p_uint8_t value) {
    brickpiJNI.i2c_struct_t_buffer_write_set(swigCPtr, this, SWIGTYPE_p_uint8_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint8_t getBuffer_write() {
    long cPtr = brickpiJNI.i2c_struct_t_buffer_write_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_uint8_t(cPtr, false);
  }

  public void setLength_read(SWIGTYPE_p_uint8_t value) {
    brickpiJNI.i2c_struct_t_length_read_set(swigCPtr, this, SWIGTYPE_p_uint8_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint8_t getLength_read() {
    return new SWIGTYPE_p_uint8_t(brickpiJNI.i2c_struct_t_length_read_get(swigCPtr, this), true);
  }

  public void setBuffer_read(SWIGTYPE_p_uint8_t value) {
    brickpiJNI.i2c_struct_t_buffer_read_set(swigCPtr, this, SWIGTYPE_p_uint8_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint8_t getBuffer_read() {
    long cPtr = brickpiJNI.i2c_struct_t_buffer_read_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_uint8_t(cPtr, false);
  }

  public i2c_struct_t() {
    this(brickpiJNI.new_i2c_struct_t(), true);
  }

}
