package com.brickpi.java;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class sensor_touch_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected sensor_touch_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(sensor_touch_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        brickpiJNI.delete_sensor_touch_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPressed(boolean value) {
    brickpiJNI.sensor_touch_t_pressed_set(swigCPtr, this, value);
  }

  public boolean getPressed() {
    return brickpiJNI.sensor_touch_t_pressed_get(swigCPtr, this);
  }

  public sensor_touch_t() {
    this(brickpiJNI.new_sensor_touch_t(), true);
  }

}
