package com.brickpi.java;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class sensor_color_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected sensor_color_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(sensor_color_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        brickpiJNI.delete_sensor_color_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setColor(SWIGTYPE_p_int8_t value) {
    brickpiJNI.sensor_color_t_color_set(swigCPtr, this, SWIGTYPE_p_int8_t.getCPtr(value));
  }

  public SWIGTYPE_p_int8_t getColor() {
    return new SWIGTYPE_p_int8_t(brickpiJNI.sensor_color_t_color_get(swigCPtr, this), true);
  }

  public void setReflected_red(SWIGTYPE_p_int16_t value) {
    brickpiJNI.sensor_color_t_reflected_red_set(swigCPtr, this, SWIGTYPE_p_int16_t.getCPtr(value));
  }

  public SWIGTYPE_p_int16_t getReflected_red() {
    return new SWIGTYPE_p_int16_t(brickpiJNI.sensor_color_t_reflected_red_get(swigCPtr, this), true);
  }

  public void setReflected_green(SWIGTYPE_p_int16_t value) {
    brickpiJNI.sensor_color_t_reflected_green_set(swigCPtr, this, SWIGTYPE_p_int16_t.getCPtr(value));
  }

  public SWIGTYPE_p_int16_t getReflected_green() {
    return new SWIGTYPE_p_int16_t(brickpiJNI.sensor_color_t_reflected_green_get(swigCPtr, this), true);
  }

  public void setReflected_blue(SWIGTYPE_p_int16_t value) {
    brickpiJNI.sensor_color_t_reflected_blue_set(swigCPtr, this, SWIGTYPE_p_int16_t.getCPtr(value));
  }

  public SWIGTYPE_p_int16_t getReflected_blue() {
    return new SWIGTYPE_p_int16_t(brickpiJNI.sensor_color_t_reflected_blue_get(swigCPtr, this), true);
  }

  public void setAmbient(SWIGTYPE_p_int16_t value) {
    brickpiJNI.sensor_color_t_ambient_set(swigCPtr, this, SWIGTYPE_p_int16_t.getCPtr(value));
  }

  public SWIGTYPE_p_int16_t getAmbient() {
    return new SWIGTYPE_p_int16_t(brickpiJNI.sensor_color_t_ambient_get(swigCPtr, this), true);
  }

  public sensor_color_t() {
    this(brickpiJNI.new_sensor_color_t(), true);
  }

}
