/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class sensor_gyro_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected sensor_gyro_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(sensor_gyro_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        brickpiJNI.delete_sensor_gyro_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setAbs(SWIGTYPE_p_int16_t value) {
    brickpiJNI.sensor_gyro_t_abs_set(swigCPtr, this, SWIGTYPE_p_int16_t.getCPtr(value));
  }

  public SWIGTYPE_p_int16_t getAbs() {
    return new SWIGTYPE_p_int16_t(brickpiJNI.sensor_gyro_t_abs_get(swigCPtr, this), true);
  }

  public void setDps(SWIGTYPE_p_int16_t value) {
    brickpiJNI.sensor_gyro_t_dps_set(swigCPtr, this, SWIGTYPE_p_int16_t.getCPtr(value));
  }

  public SWIGTYPE_p_int16_t getDps() {
    return new SWIGTYPE_p_int16_t(brickpiJNI.sensor_gyro_t_dps_get(swigCPtr, this), true);
  }

  public sensor_gyro_t() {
    this(brickpiJNI.new_sensor_gyro_t(), true);
  }

}
