/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class SENSOR_CONFIG_FLAGS {
  public final static SENSOR_CONFIG_FLAGS SENSOR_CONFIG_I2C_MID_CLOCK = new SENSOR_CONFIG_FLAGS("SENSOR_CONFIG_I2C_MID_CLOCK", brickpiJNI.SENSOR_CONFIG_I2C_MID_CLOCK_get());
  public final static SENSOR_CONFIG_FLAGS SENSOR_CONFIG_PIN_1_PULL = new SENSOR_CONFIG_FLAGS("SENSOR_CONFIG_PIN_1_PULL", brickpiJNI.SENSOR_CONFIG_PIN_1_PULL_get());
  public final static SENSOR_CONFIG_FLAGS SENSOR_CONFIG_I2C_REPEAT = new SENSOR_CONFIG_FLAGS("SENSOR_CONFIG_I2C_REPEAT", brickpiJNI.SENSOR_CONFIG_I2C_REPEAT_get());
  public final static SENSOR_CONFIG_FLAGS SENSOR_CONFIG_PIN_5_DIR = new SENSOR_CONFIG_FLAGS("SENSOR_CONFIG_PIN_5_DIR", brickpiJNI.SENSOR_CONFIG_PIN_5_DIR_get());
  public final static SENSOR_CONFIG_FLAGS SENSOR_CONFIG_PIN_5_STATE = new SENSOR_CONFIG_FLAGS("SENSOR_CONFIG_PIN_5_STATE", brickpiJNI.SENSOR_CONFIG_PIN_5_STATE_get());
  public final static SENSOR_CONFIG_FLAGS SENSOR_CONFIG_PIN_6_DIR = new SENSOR_CONFIG_FLAGS("SENSOR_CONFIG_PIN_6_DIR", brickpiJNI.SENSOR_CONFIG_PIN_6_DIR_get());
  public final static SENSOR_CONFIG_FLAGS SENSOR_CONFIG_PIN_6_STATE = new SENSOR_CONFIG_FLAGS("SENSOR_CONFIG_PIN_6_STATE", brickpiJNI.SENSOR_CONFIG_PIN_6_STATE_get());
  public final static SENSOR_CONFIG_FLAGS SENSOR_CONFIG_REPORT_1_ADC = new SENSOR_CONFIG_FLAGS("SENSOR_CONFIG_REPORT_1_ADC", brickpiJNI.SENSOR_CONFIG_REPORT_1_ADC_get());
  public final static SENSOR_CONFIG_FLAGS SENSOR_CONFIG_REPORT_6_ADC = new SENSOR_CONFIG_FLAGS("SENSOR_CONFIG_REPORT_6_ADC", brickpiJNI.SENSOR_CONFIG_REPORT_6_ADC_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static SENSOR_CONFIG_FLAGS swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + SENSOR_CONFIG_FLAGS.class + " with value " + swigValue);
  }

  private SENSOR_CONFIG_FLAGS(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private SENSOR_CONFIG_FLAGS(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private SENSOR_CONFIG_FLAGS(String swigName, SENSOR_CONFIG_FLAGS swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static SENSOR_CONFIG_FLAGS[] swigValues = { SENSOR_CONFIG_I2C_MID_CLOCK, SENSOR_CONFIG_PIN_1_PULL, SENSOR_CONFIG_I2C_REPEAT, SENSOR_CONFIG_PIN_5_DIR, SENSOR_CONFIG_PIN_5_STATE, SENSOR_CONFIG_PIN_6_DIR, SENSOR_CONFIG_PIN_6_STATE, SENSOR_CONFIG_REPORT_1_ADC, SENSOR_CONFIG_REPORT_6_ADC };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

