/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class SENSOR_TYPE {
  public final static SENSOR_TYPE SENSOR_TYPE_NONE = new SENSOR_TYPE("SENSOR_TYPE_NONE", brickpiJNI.SENSOR_TYPE_NONE_get());
  public final static SENSOR_TYPE SENSOR_TYPE_I2C = new SENSOR_TYPE("SENSOR_TYPE_I2C");
  public final static SENSOR_TYPE SENSOR_TYPE_CUSTOM = new SENSOR_TYPE("SENSOR_TYPE_CUSTOM");
  public final static SENSOR_TYPE SENSOR_TYPE_TOUCH = new SENSOR_TYPE("SENSOR_TYPE_TOUCH");
  public final static SENSOR_TYPE SENSOR_TYPE_TOUCH_NXT = new SENSOR_TYPE("SENSOR_TYPE_TOUCH_NXT");
  public final static SENSOR_TYPE SENSOR_TYPE_TOUCH_EV3 = new SENSOR_TYPE("SENSOR_TYPE_TOUCH_EV3");
  public final static SENSOR_TYPE SENSOR_TYPE_NXT_LIGHT_ON = new SENSOR_TYPE("SENSOR_TYPE_NXT_LIGHT_ON");
  public final static SENSOR_TYPE SENSOR_TYPE_NXT_LIGHT_OFF = new SENSOR_TYPE("SENSOR_TYPE_NXT_LIGHT_OFF");
  public final static SENSOR_TYPE SENSOR_TYPE_NXT_COLOR_RED = new SENSOR_TYPE("SENSOR_TYPE_NXT_COLOR_RED");
  public final static SENSOR_TYPE SENSOR_TYPE_NXT_COLOR_GREEN = new SENSOR_TYPE("SENSOR_TYPE_NXT_COLOR_GREEN");
  public final static SENSOR_TYPE SENSOR_TYPE_NXT_COLOR_BLUE = new SENSOR_TYPE("SENSOR_TYPE_NXT_COLOR_BLUE");
  public final static SENSOR_TYPE SENSOR_TYPE_NXT_COLOR_FULL = new SENSOR_TYPE("SENSOR_TYPE_NXT_COLOR_FULL");
  public final static SENSOR_TYPE SENSOR_TYPE_NXT_COLOR_OFF = new SENSOR_TYPE("SENSOR_TYPE_NXT_COLOR_OFF");
  public final static SENSOR_TYPE SENSOR_TYPE_NXT_ULTRASONIC = new SENSOR_TYPE("SENSOR_TYPE_NXT_ULTRASONIC");
  public final static SENSOR_TYPE SENSOR_TYPE_EV3_GYRO_ABS = new SENSOR_TYPE("SENSOR_TYPE_EV3_GYRO_ABS");
  public final static SENSOR_TYPE SENSOR_TYPE_EV3_GYRO_DPS = new SENSOR_TYPE("SENSOR_TYPE_EV3_GYRO_DPS");
  public final static SENSOR_TYPE SENSOR_TYPE_EV3_GYRO_ABS_DPS = new SENSOR_TYPE("SENSOR_TYPE_EV3_GYRO_ABS_DPS");
  public final static SENSOR_TYPE SENSOR_TYPE_EV3_COLOR_REFLECTED = new SENSOR_TYPE("SENSOR_TYPE_EV3_COLOR_REFLECTED");
  public final static SENSOR_TYPE SENSOR_TYPE_EV3_COLOR_AMBIENT = new SENSOR_TYPE("SENSOR_TYPE_EV3_COLOR_AMBIENT");
  public final static SENSOR_TYPE SENSOR_TYPE_EV3_COLOR_COLOR = new SENSOR_TYPE("SENSOR_TYPE_EV3_COLOR_COLOR");
  public final static SENSOR_TYPE SENSOR_TYPE_EV3_COLOR_RAW_REFLECTED = new SENSOR_TYPE("SENSOR_TYPE_EV3_COLOR_RAW_REFLECTED");
  public final static SENSOR_TYPE SENSOR_TYPE_EV3_COLOR_COLOR_COMPONENTS = new SENSOR_TYPE("SENSOR_TYPE_EV3_COLOR_COLOR_COMPONENTS");
  public final static SENSOR_TYPE SENSOR_TYPE_EV3_ULTRASONIC_CM = new SENSOR_TYPE("SENSOR_TYPE_EV3_ULTRASONIC_CM");
  public final static SENSOR_TYPE SENSOR_TYPE_EV3_ULTRASONIC_INCHES = new SENSOR_TYPE("SENSOR_TYPE_EV3_ULTRASONIC_INCHES");
  public final static SENSOR_TYPE SENSOR_TYPE_EV3_ULTRASONIC_LISTEN = new SENSOR_TYPE("SENSOR_TYPE_EV3_ULTRASONIC_LISTEN");
  public final static SENSOR_TYPE SENSOR_TYPE_EV3_INFRARED_PROXIMITY = new SENSOR_TYPE("SENSOR_TYPE_EV3_INFRARED_PROXIMITY");
  public final static SENSOR_TYPE SENSOR_TYPE_EV3_INFRARED_SEEK = new SENSOR_TYPE("SENSOR_TYPE_EV3_INFRARED_SEEK");
  public final static SENSOR_TYPE SENSOR_TYPE_EV3_INFRARED_REMOTE = new SENSOR_TYPE("SENSOR_TYPE_EV3_INFRARED_REMOTE");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static SENSOR_TYPE swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + SENSOR_TYPE.class + " with value " + swigValue);
  }

  private SENSOR_TYPE(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private SENSOR_TYPE(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private SENSOR_TYPE(String swigName, SENSOR_TYPE swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static SENSOR_TYPE[] swigValues = { SENSOR_TYPE_NONE, SENSOR_TYPE_I2C, SENSOR_TYPE_CUSTOM, SENSOR_TYPE_TOUCH, SENSOR_TYPE_TOUCH_NXT, SENSOR_TYPE_TOUCH_EV3, SENSOR_TYPE_NXT_LIGHT_ON, SENSOR_TYPE_NXT_LIGHT_OFF, SENSOR_TYPE_NXT_COLOR_RED, SENSOR_TYPE_NXT_COLOR_GREEN, SENSOR_TYPE_NXT_COLOR_BLUE, SENSOR_TYPE_NXT_COLOR_FULL, SENSOR_TYPE_NXT_COLOR_OFF, SENSOR_TYPE_NXT_ULTRASONIC, SENSOR_TYPE_EV3_GYRO_ABS, SENSOR_TYPE_EV3_GYRO_DPS, SENSOR_TYPE_EV3_GYRO_ABS_DPS, SENSOR_TYPE_EV3_COLOR_REFLECTED, SENSOR_TYPE_EV3_COLOR_AMBIENT, SENSOR_TYPE_EV3_COLOR_COLOR, SENSOR_TYPE_EV3_COLOR_RAW_REFLECTED, SENSOR_TYPE_EV3_COLOR_COLOR_COMPONENTS, SENSOR_TYPE_EV3_ULTRASONIC_CM, SENSOR_TYPE_EV3_ULTRASONIC_INCHES, SENSOR_TYPE_EV3_ULTRASONIC_LISTEN, SENSOR_TYPE_EV3_INFRARED_PROXIMITY, SENSOR_TYPE_EV3_INFRARED_SEEK, SENSOR_TYPE_EV3_INFRARED_REMOTE };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

