/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.brickpi3.java;

public interface brickpiConstants {
  public final static String FIRMWARE_VERSION_REQUIRED = brickpiJNI.FIRMWARE_VERSION_REQUIRED_get();
  public final static int LONGEST_SPI_TRANSFER = brickpiJNI.LONGEST_SPI_TRANSFER_get();
  public final static int LONGEST_I2C_TRANSFER = brickpiJNI.LONGEST_I2C_TRANSFER_get();
  public final static int SPI_TARGET_SPEED = brickpiJNI.SPI_TARGET_SPEED_get();
  public final static String SPIDEV_FILE_NAME = brickpiJNI.SPIDEV_FILE_NAME_get();
  public final static int ERROR_NONE = brickpiJNI.ERROR_NONE_get();
  public final static int ERROR_SPI_FILE = brickpiJNI.ERROR_SPI_FILE_get();
  public final static int ERROR_SPI_RESPONSE = brickpiJNI.ERROR_SPI_RESPONSE_get();
  public final static int ERROR_WRONG_MANUFACTURER = brickpiJNI.ERROR_WRONG_MANUFACTURER_get();
  public final static int ERROR_WRONG_DEVICE = brickpiJNI.ERROR_WRONG_DEVICE_get();
  public final static int ERROR_FIRMWARE_MISMATCH = brickpiJNI.ERROR_FIRMWARE_MISMATCH_get();
  public final static int ERROR_SENSOR_TYPE_MISMATCH = brickpiJNI.ERROR_SENSOR_TYPE_MISMATCH_get();
  public final static int PORT_1 = brickpiJNI.PORT_1_get();
  public final static int PORT_2 = brickpiJNI.PORT_2_get();
  public final static int PORT_3 = brickpiJNI.PORT_3_get();
  public final static int PORT_4 = brickpiJNI.PORT_4_get();
  public final static int PORT_A = brickpiJNI.PORT_A_get();
  public final static int PORT_B = brickpiJNI.PORT_B_get();
  public final static int PORT_C = brickpiJNI.PORT_C_get();
  public final static int PORT_D = brickpiJNI.PORT_D_get();
  public final static int MOTOR_FLOAT = brickpiJNI.MOTOR_FLOAT_get();
  public final static int REMOTE_BIT_RED_UP = brickpiJNI.REMOTE_BIT_RED_UP_get();
  public final static int REMOTE_BIT_RED_DOWN = brickpiJNI.REMOTE_BIT_RED_DOWN_get();
  public final static int REMOTE_BIT_BLUE_UP = brickpiJNI.REMOTE_BIT_BLUE_UP_get();
  public final static int REMOTE_BIT_BLUE_DOWN = brickpiJNI.REMOTE_BIT_BLUE_DOWN_get();
  public final static int REMOTE_BIT_BROADCAST = brickpiJNI.REMOTE_BIT_BROADCAST_get();
}
