/*
 * ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * -----------------------------------------------------------------------------
 */

package com.brickpi3.java;

public class brickpiJNI {
  static {
    boolean loaded = false;
    Throwable[] errors = new Throwable[4];

    try {
      LibraryExtractionHelper.extractResourceToHome("libbrickpi.so");
      System.load(
          LibraryExtractionHelper.getHomeFile(".brickpi3java", "libbrickpi.so").getAbsolutePath());
      System.out.println("Loaded home resource");
      loaded = true;
    } catch (Exception | Error e) {
      errors[0] = e;
    }

    try {
      System.load(brickpiJNI.class.getClassLoader().getResource("libbrickpi.so").getFile());
      System.out.println("Loaded resource");
      loaded = true;
    } catch (Exception | Error e) {
      errors[1] = e;
    }

    try {
      if (!loaded) {
        System.loadLibrary("libbrickpi");
        System.out.println("Loaded from path");
      }
      loaded = true;
    } catch (Exception | Error e) {
      errors[2] = e;
    }

    try {
      if (!loaded) {
        System.load("/usr/lib/libbrickpi.so");
        System.out.println("Loaded from usr lib");
      }
      loaded = true;
    } catch (Exception | Error e) {
      errors[3] = e;
    }

    if (!loaded) {
      for (Throwable e : errors) {
        if (e != null)
          e.printStackTrace();
      }
    }
  }

  public final static native String FIRMWARE_VERSION_REQUIRED_get();

  public final static native int LONGEST_SPI_TRANSFER_get();

  public final static native int LONGEST_I2C_TRANSFER_get();

  public final static native int SPI_TARGET_SPEED_get();

  public final static native String SPIDEV_FILE_NAME_get();

  public final static native int ERROR_NONE_get();

  public final static native int ERROR_SPI_FILE_get();

  public final static native int ERROR_SPI_RESPONSE_get();

  public final static native int ERROR_WRONG_MANUFACTURER_get();

  public final static native int ERROR_WRONG_DEVICE_get();

  public final static native int ERROR_FIRMWARE_MISMATCH_get();

  public final static native int ERROR_SENSOR_TYPE_MISMATCH_get();

  public final static native void spi_file_handle_set(int jarg1);

  public final static native int spi_file_handle_get();

  public final static native void spi_xfer_struct_set(long jarg1);

  public final static native long spi_xfer_struct_get();

  public final static native void spi_array_out_set(long jarg1);

  public final static native long spi_array_out_get();

  public final static native void spi_array_in_set(long jarg1);

  public final static native long spi_array_in_get();

  public final static native int spi_setup();

  public final static native int spi_transfer_array(long jarg1, long jarg2, long jarg3);

  public final static native void fatal_error__SWIG_0(String jarg1);

  public final static native int SENSOR_TYPE_NONE_get();

  public final static native int SENSOR_CONFIG_I2C_MID_CLOCK_get();

  public final static native int SENSOR_CONFIG_PIN_1_PULL_get();

  public final static native int SENSOR_CONFIG_I2C_REPEAT_get();

  public final static native int SENSOR_CONFIG_PIN_5_DIR_get();

  public final static native int SENSOR_CONFIG_PIN_5_STATE_get();

  public final static native int SENSOR_CONFIG_PIN_6_DIR_get();

  public final static native int SENSOR_CONFIG_PIN_6_STATE_get();

  public final static native int SENSOR_CONFIG_REPORT_1_ADC_get();

  public final static native int SENSOR_CONFIG_REPORT_6_ADC_get();

  public final static native int PORT_1_get();

  public final static native int PORT_2_get();

  public final static native int PORT_3_get();

  public final static native int PORT_4_get();

  public final static native int PORT_A_get();

  public final static native int PORT_B_get();

  public final static native int PORT_C_get();

  public final static native int PORT_D_get();

  public final static native int MOTOR_FLOAT_get();

  public final static native int REMOTE_BIT_RED_UP_get();

  public final static native int REMOTE_BIT_RED_DOWN_get();

  public final static native int REMOTE_BIT_BLUE_UP_get();

  public final static native int REMOTE_BIT_BLUE_DOWN_get();

  public final static native int REMOTE_BIT_BROADCAST_get();

  public final static native void i2c_struct_t_speed_set(long jarg1, i2c_struct_t jarg1_,
      long jarg2);

  public final static native long i2c_struct_t_speed_get(long jarg1, i2c_struct_t jarg1_);

  public final static native void i2c_struct_t_delay_set(long jarg1, i2c_struct_t jarg1_,
      long jarg2);

  public final static native long i2c_struct_t_delay_get(long jarg1, i2c_struct_t jarg1_);

  public final static native void i2c_struct_t_address_set(long jarg1, i2c_struct_t jarg1_,
      long jarg2);

  public final static native long i2c_struct_t_address_get(long jarg1, i2c_struct_t jarg1_);

  public final static native void i2c_struct_t_length_write_set(long jarg1, i2c_struct_t jarg1_,
      long jarg2);

  public final static native long i2c_struct_t_length_write_get(long jarg1, i2c_struct_t jarg1_);

  public final static native void i2c_struct_t_buffer_write_set(long jarg1, i2c_struct_t jarg1_,
      long jarg2);

  public final static native long i2c_struct_t_buffer_write_get(long jarg1, i2c_struct_t jarg1_);

  public final static native void i2c_struct_t_length_read_set(long jarg1, i2c_struct_t jarg1_,
      long jarg2);

  public final static native long i2c_struct_t_length_read_get(long jarg1, i2c_struct_t jarg1_);

  public final static native void i2c_struct_t_buffer_read_set(long jarg1, i2c_struct_t jarg1_,
      long jarg2);

  public final static native long i2c_struct_t_buffer_read_get(long jarg1, i2c_struct_t jarg1_);

  public final static native long new_i2c_struct_t();

  public final static native void delete_i2c_struct_t(long jarg1);

  public final static native void sensor_custom_t_adc1_set(long jarg1, sensor_custom_t jarg1_,
      long jarg2);

  public final static native long sensor_custom_t_adc1_get(long jarg1, sensor_custom_t jarg1_);

  public final static native void sensor_custom_t_adc6_set(long jarg1, sensor_custom_t jarg1_,
      long jarg2);

  public final static native long sensor_custom_t_adc6_get(long jarg1, sensor_custom_t jarg1_);

  public final static native void sensor_custom_t_pin5_set(long jarg1, sensor_custom_t jarg1_,
      boolean jarg2);

  public final static native boolean sensor_custom_t_pin5_get(long jarg1, sensor_custom_t jarg1_);

  public final static native void sensor_custom_t_pin6_set(long jarg1, sensor_custom_t jarg1_,
      boolean jarg2);

  public final static native boolean sensor_custom_t_pin6_get(long jarg1, sensor_custom_t jarg1_);

  public final static native long new_sensor_custom_t();

  public final static native void delete_sensor_custom_t(long jarg1);

  public final static native void sensor_touch_t_pressed_set(long jarg1, sensor_touch_t jarg1_,
      boolean jarg2);

  public final static native boolean sensor_touch_t_pressed_get(long jarg1, sensor_touch_t jarg1_);

  public final static native long new_sensor_touch_t();

  public final static native void delete_sensor_touch_t(long jarg1);

  public final static native void sensor_light_t_ambient_set(long jarg1, sensor_light_t jarg1_,
      long jarg2);

  public final static native long sensor_light_t_ambient_get(long jarg1, sensor_light_t jarg1_);

  public final static native void sensor_light_t_reflected_set(long jarg1, sensor_light_t jarg1_,
      long jarg2);

  public final static native long sensor_light_t_reflected_get(long jarg1, sensor_light_t jarg1_);

  public final static native long new_sensor_light_t();

  public final static native void delete_sensor_light_t(long jarg1);

  public final static native void sensor_color_t_color_set(long jarg1, sensor_color_t jarg1_,
      long jarg2);

  public final static native long sensor_color_t_color_get(long jarg1, sensor_color_t jarg1_);

  public final static native void sensor_color_t_reflected_red_set(long jarg1,
      sensor_color_t jarg1_, long jarg2);

  public final static native long sensor_color_t_reflected_red_get(long jarg1,
      sensor_color_t jarg1_);

  public final static native void sensor_color_t_reflected_green_set(long jarg1,
      sensor_color_t jarg1_, long jarg2);

  public final static native long sensor_color_t_reflected_green_get(long jarg1,
      sensor_color_t jarg1_);

  public final static native void sensor_color_t_reflected_blue_set(long jarg1,
      sensor_color_t jarg1_, long jarg2);

  public final static native long sensor_color_t_reflected_blue_get(long jarg1,
      sensor_color_t jarg1_);

  public final static native void sensor_color_t_ambient_set(long jarg1, sensor_color_t jarg1_,
      long jarg2);

  public final static native long sensor_color_t_ambient_get(long jarg1, sensor_color_t jarg1_);

  public final static native long new_sensor_color_t();

  public final static native void delete_sensor_color_t(long jarg1);

  public final static native void sensor_ultrasonic_t_cm_set(long jarg1, sensor_ultrasonic_t jarg1_,
      float jarg2);

  public final static native float sensor_ultrasonic_t_cm_get(long jarg1,
      sensor_ultrasonic_t jarg1_);

  public final static native void sensor_ultrasonic_t_inch_set(long jarg1,
      sensor_ultrasonic_t jarg1_, float jarg2);

  public final static native float sensor_ultrasonic_t_inch_get(long jarg1,
      sensor_ultrasonic_t jarg1_);

  public final static native void sensor_ultrasonic_t_presence_set(long jarg1,
      sensor_ultrasonic_t jarg1_, boolean jarg2);

  public final static native boolean sensor_ultrasonic_t_presence_get(long jarg1,
      sensor_ultrasonic_t jarg1_);

  public final static native long new_sensor_ultrasonic_t();

  public final static native void delete_sensor_ultrasonic_t(long jarg1);

  public final static native void sensor_gyro_t_abs_set(long jarg1, sensor_gyro_t jarg1_,
      long jarg2);

  public final static native long sensor_gyro_t_abs_get(long jarg1, sensor_gyro_t jarg1_);

  public final static native void sensor_gyro_t_dps_set(long jarg1, sensor_gyro_t jarg1_,
      long jarg2);

  public final static native long sensor_gyro_t_dps_get(long jarg1, sensor_gyro_t jarg1_);

  public final static native long new_sensor_gyro_t();

  public final static native void delete_sensor_gyro_t(long jarg1);

  public final static native void sensor_infrared_t_proximity_set(long jarg1,
      sensor_infrared_t jarg1_, long jarg2);

  public final static native long sensor_infrared_t_proximity_get(long jarg1,
      sensor_infrared_t jarg1_);

  public final static native void sensor_infrared_t_distance_set(long jarg1,
      sensor_infrared_t jarg1_, long jarg2);

  public final static native long sensor_infrared_t_distance_get(long jarg1,
      sensor_infrared_t jarg1_);

  public final static native void sensor_infrared_t_heading_set(long jarg1,
      sensor_infrared_t jarg1_, long jarg2);

  public final static native long sensor_infrared_t_heading_get(long jarg1,
      sensor_infrared_t jarg1_);

  public final static native void sensor_infrared_t_remote_set(long jarg1, sensor_infrared_t jarg1_,
      long jarg2);

  public final static native long sensor_infrared_t_remote_get(long jarg1,
      sensor_infrared_t jarg1_);

  public final static native long new_sensor_infrared_t();

  public final static native void delete_sensor_infrared_t(long jarg1);

  public final static native int BrickPi3_set_address(int jarg1, String jarg2);

  public final static native long new_BrickPi3__SWIG_0(long jarg1);

  public final static native long new_BrickPi3__SWIG_1();

  public final static native int BrickPi3_detect__SWIG_0(long jarg1, BrickPi3 jarg1_,
      boolean jarg2);

  public final static native int BrickPi3_detect__SWIG_1(long jarg1, BrickPi3 jarg1_);

  public final static native int BrickPi3_get_manufacturer(long jarg1, BrickPi3 jarg1_,
      String jarg2);

  public final static native int BrickPi3_get_board(long jarg1, BrickPi3 jarg1_, String jarg2);

  public final static native int BrickPi3_get_version_hardware(long jarg1, BrickPi3 jarg1_,
      String jarg2);

  public final static native int BrickPi3_get_version_firmware(long jarg1, BrickPi3 jarg1_,
      String jarg2);

  public final static native int BrickPi3_get_id(long jarg1, BrickPi3 jarg1_, String jarg2);

  public final static native int BrickPi3_set_led(long jarg1, BrickPi3 jarg1_, long jarg2);

  public final static native float BrickPi3_get_voltage_3v3__SWIG_0(long jarg1, BrickPi3 jarg1_);

  public final static native float BrickPi3_get_voltage_5v__SWIG_0(long jarg1, BrickPi3 jarg1_);

  public final static native float BrickPi3_get_voltage_9v__SWIG_0(long jarg1, BrickPi3 jarg1_);

  public final static native float BrickPi3_get_voltage_battery__SWIG_0(long jarg1,
      BrickPi3 jarg1_);

  public final static native int BrickPi3_get_voltage_3v3__SWIG_1(long jarg1, BrickPi3 jarg1_,
      long jarg2);

  public final static native int BrickPi3_get_voltage_5v__SWIG_1(long jarg1, BrickPi3 jarg1_,
      long jarg2);

  public final static native int BrickPi3_get_voltage_9v__SWIG_1(long jarg1, BrickPi3 jarg1_,
      long jarg2);

  public final static native int BrickPi3_get_voltage_battery__SWIG_1(long jarg1, BrickPi3 jarg1_,
      long jarg2);

  public final static native int BrickPi3_set_sensor_type__SWIG_0(long jarg1, BrickPi3 jarg1_,
      long jarg2, long jarg3, long jarg4, long jarg5, i2c_struct_t jarg5_);

  public final static native int BrickPi3_set_sensor_type__SWIG_1(long jarg1, BrickPi3 jarg1_,
      long jarg2, long jarg3, long jarg4);

  public final static native int BrickPi3_set_sensor_type__SWIG_2(long jarg1, BrickPi3 jarg1_,
      long jarg2, long jarg3);

  public final static native int BrickPi3_transact_i2c(long jarg1, BrickPi3 jarg1_, long jarg2,
      long jarg3, i2c_struct_t jarg3_);

  public final static native int BrickPi3_get_sensor(long jarg1, BrickPi3 jarg1_, long jarg2,
      long jarg3);

  public final static native int BrickPi3_set_motor_power(long jarg1, BrickPi3 jarg1_, long jarg2,
      long jarg3);

  public final static native int BrickPi3_set_motor_position(long jarg1, BrickPi3 jarg1_,
      long jarg2, long jarg3);

  public final static native int BrickPi3_set_motor_position_relative(long jarg1, BrickPi3 jarg1_,
      long jarg2, long jarg3);

  public final static native int BrickPi3_set_motor_dps(long jarg1, BrickPi3 jarg1_, long jarg2,
      long jarg3);

  public final static native int BrickPi3_set_motor_limits(long jarg1, BrickPi3 jarg1_, long jarg2,
      long jarg3, long jarg4);

  public final static native int BrickPi3_get_motor_status(long jarg1, BrickPi3 jarg1_, long jarg2,
      long jarg3, long jarg4, long jarg5, long jarg6);

  public final static native int BrickPi3_offset_motor_encoder(long jarg1, BrickPi3 jarg1_,
      long jarg2, long jarg3);

  public final static native int BrickPi3_reset_motor_encoder__SWIG_0(long jarg1, BrickPi3 jarg1_,
      long jarg2, long jarg3);

  public final static native int BrickPi3_reset_motor_encoder__SWIG_1(long jarg1, BrickPi3 jarg1_,
      long jarg2);

  public final static native int BrickPi3_set_motor_encoder(long jarg1, BrickPi3 jarg1_, long jarg2,
      long jarg3);

  public final static native int BrickPi3_get_motor_encoder__SWIG_0(long jarg1, BrickPi3 jarg1_,
      long jarg2, long jarg3);

  public final static native long BrickPi3_get_motor_encoder__SWIG_1(long jarg1, BrickPi3 jarg1_,
      long jarg2);

  public final static native int BrickPi3_reset_all(long jarg1, BrickPi3 jarg1_);

  public final static native void delete_BrickPi3(long jarg1);
}
