/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.brickpi3.java;

public class brickpi implements brickpiConstants {
  public static void setSpi_file_handle(int value) {
    brickpiJNI.spi_file_handle_set(value);
  }

  public static int getSpi_file_handle() {
    return brickpiJNI.spi_file_handle_get();
  }

  public static void setSpi_xfer_struct(SWIGTYPE_p_spi_ioc_transfer value) {
    brickpiJNI.spi_xfer_struct_set(SWIGTYPE_p_spi_ioc_transfer.getCPtr(value));
  }

  public static SWIGTYPE_p_spi_ioc_transfer getSpi_xfer_struct() {
    return new SWIGTYPE_p_spi_ioc_transfer(brickpiJNI.spi_xfer_struct_get(), true);
  }

  public static void setSpi_array_out(SWIGTYPE_p_uint8_t value) {
    brickpiJNI.spi_array_out_set(SWIGTYPE_p_uint8_t.getCPtr(value));
  }

  public static SWIGTYPE_p_uint8_t getSpi_array_out() {
    long cPtr = brickpiJNI.spi_array_out_get();
    return (cPtr == 0) ? null : new SWIGTYPE_p_uint8_t(cPtr, false);
  }

  public static void setSpi_array_in(SWIGTYPE_p_uint8_t value) {
    brickpiJNI.spi_array_in_set(SWIGTYPE_p_uint8_t.getCPtr(value));
  }

  public static SWIGTYPE_p_uint8_t getSpi_array_in() {
    long cPtr = brickpiJNI.spi_array_in_get();
    return (cPtr == 0) ? null : new SWIGTYPE_p_uint8_t(cPtr, false);
  }

  public static int spi_setup() {
    return brickpiJNI.spi_setup();
  }

  public static int spi_transfer_array(SWIGTYPE_p_uint8_t length, SWIGTYPE_p_uint8_t outArray, SWIGTYPE_p_uint8_t inArray) {
    return brickpiJNI.spi_transfer_array(SWIGTYPE_p_uint8_t.getCPtr(length), SWIGTYPE_p_uint8_t.getCPtr(outArray), SWIGTYPE_p_uint8_t.getCPtr(inArray));
  }

  public static void fatal_error(String error) {
    brickpiJNI.fatal_error__SWIG_0(error);
  }

  public static int BrickPi3_set_address(int addr, String id) {
    return brickpiJNI.BrickPi3_set_address(addr, id);
  }

  public static SWIGTYPE_p_float new_floatp() {
    long cPtr = brickpiJNI.new_floatp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

  public static SWIGTYPE_p_float copy_floatp(float value) {
    long cPtr = brickpiJNI.copy_floatp(value);
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

  public static void delete_floatp(SWIGTYPE_p_float obj) {
    brickpiJNI.delete_floatp(SWIGTYPE_p_float.getCPtr(obj));
  }

  public static void floatp_assign(SWIGTYPE_p_float obj, float value) {
    brickpiJNI.floatp_assign(SWIGTYPE_p_float.getCPtr(obj), value);
  }

  public static float floatp_value(SWIGTYPE_p_float obj) {
    return brickpiJNI.floatp_value(SWIGTYPE_p_float.getCPtr(obj));
  }

  public static SWIGTYPE_p_int16_t new_int16_tp() {
    long cPtr = brickpiJNI.new_int16_tp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_int16_t(cPtr, false);
  }

  public static SWIGTYPE_p_int16_t copy_int16_tp(SWIGTYPE_p_int16_t value) {
    long cPtr = brickpiJNI.copy_int16_tp(SWIGTYPE_p_int16_t.getCPtr(value));
    return (cPtr == 0) ? null : new SWIGTYPE_p_int16_t(cPtr, false);
  }

  public static void delete_int16_tp(SWIGTYPE_p_int16_t obj) {
    brickpiJNI.delete_int16_tp(SWIGTYPE_p_int16_t.getCPtr(obj));
  }

  public static void int16_tp_assign(SWIGTYPE_p_int16_t obj, SWIGTYPE_p_int16_t value) {
    brickpiJNI.int16_tp_assign(SWIGTYPE_p_int16_t.getCPtr(obj), SWIGTYPE_p_int16_t.getCPtr(value));
  }

  public static SWIGTYPE_p_int16_t int16_tp_value(SWIGTYPE_p_int16_t obj) {
    return new SWIGTYPE_p_int16_t(brickpiJNI.int16_tp_value(SWIGTYPE_p_int16_t.getCPtr(obj)), true);
  }

  public static SWIGTYPE_p_int32_t new_int32_tp() {
    long cPtr = brickpiJNI.new_int32_tp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_int32_t(cPtr, false);
  }

  public static SWIGTYPE_p_int32_t copy_int32_tp(SWIGTYPE_p_int32_t value) {
    long cPtr = brickpiJNI.copy_int32_tp(SWIGTYPE_p_int32_t.getCPtr(value));
    return (cPtr == 0) ? null : new SWIGTYPE_p_int32_t(cPtr, false);
  }

  public static void delete_int32_tp(SWIGTYPE_p_int32_t obj) {
    brickpiJNI.delete_int32_tp(SWIGTYPE_p_int32_t.getCPtr(obj));
  }

  public static void int32_tp_assign(SWIGTYPE_p_int32_t obj, SWIGTYPE_p_int32_t value) {
    brickpiJNI.int32_tp_assign(SWIGTYPE_p_int32_t.getCPtr(obj), SWIGTYPE_p_int32_t.getCPtr(value));
  }

  public static SWIGTYPE_p_int32_t int32_tp_value(SWIGTYPE_p_int32_t obj) {
    return new SWIGTYPE_p_int32_t(brickpiJNI.int32_tp_value(SWIGTYPE_p_int32_t.getCPtr(obj)), true);
  }

  public static SWIGTYPE_p_int8_t new_int8_tp() {
    long cPtr = brickpiJNI.new_int8_tp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_int8_t(cPtr, false);
  }

  public static SWIGTYPE_p_int8_t copy_int8_tp(SWIGTYPE_p_int8_t value) {
    long cPtr = brickpiJNI.copy_int8_tp(SWIGTYPE_p_int8_t.getCPtr(value));
    return (cPtr == 0) ? null : new SWIGTYPE_p_int8_t(cPtr, false);
  }

  public static void delete_int8_tp(SWIGTYPE_p_int8_t obj) {
    brickpiJNI.delete_int8_tp(SWIGTYPE_p_int8_t.getCPtr(obj));
  }

  public static void int8_tp_assign(SWIGTYPE_p_int8_t obj, SWIGTYPE_p_int8_t value) {
    brickpiJNI.int8_tp_assign(SWIGTYPE_p_int8_t.getCPtr(obj), SWIGTYPE_p_int8_t.getCPtr(value));
  }

  public static SWIGTYPE_p_int8_t int8_tp_value(SWIGTYPE_p_int8_t obj) {
    return new SWIGTYPE_p_int8_t(brickpiJNI.int8_tp_value(SWIGTYPE_p_int8_t.getCPtr(obj)), true);
  }

  public static SWIGTYPE_p_uint16_t new_uint16_tp() {
    long cPtr = brickpiJNI.new_uint16_tp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_uint16_t(cPtr, false);
  }

  public static SWIGTYPE_p_uint16_t copy_uint16_tp(SWIGTYPE_p_uint16_t value) {
    long cPtr = brickpiJNI.copy_uint16_tp(SWIGTYPE_p_uint16_t.getCPtr(value));
    return (cPtr == 0) ? null : new SWIGTYPE_p_uint16_t(cPtr, false);
  }

  public static void delete_uint16_tp(SWIGTYPE_p_uint16_t obj) {
    brickpiJNI.delete_uint16_tp(SWIGTYPE_p_uint16_t.getCPtr(obj));
  }

  public static void uint16_tp_assign(SWIGTYPE_p_uint16_t obj, SWIGTYPE_p_uint16_t value) {
    brickpiJNI.uint16_tp_assign(SWIGTYPE_p_uint16_t.getCPtr(obj), SWIGTYPE_p_uint16_t.getCPtr(value));
  }

  public static SWIGTYPE_p_uint16_t uint16_tp_value(SWIGTYPE_p_uint16_t obj) {
    return new SWIGTYPE_p_uint16_t(brickpiJNI.uint16_tp_value(SWIGTYPE_p_uint16_t.getCPtr(obj)), true);
  }

  public static SWIGTYPE_p_uint8_t new_uint8_tp() {
    long cPtr = brickpiJNI.new_uint8_tp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_uint8_t(cPtr, false);
  }

  public static SWIGTYPE_p_uint8_t copy_uint8_tp(SWIGTYPE_p_uint8_t value) {
    long cPtr = brickpiJNI.copy_uint8_tp(SWIGTYPE_p_uint8_t.getCPtr(value));
    return (cPtr == 0) ? null : new SWIGTYPE_p_uint8_t(cPtr, false);
  }

  public static void delete_uint8_tp(SWIGTYPE_p_uint8_t obj) {
    brickpiJNI.delete_uint8_tp(SWIGTYPE_p_uint8_t.getCPtr(obj));
  }

  public static void uint8_tp_assign(SWIGTYPE_p_uint8_t obj, SWIGTYPE_p_uint8_t value) {
    brickpiJNI.uint8_tp_assign(SWIGTYPE_p_uint8_t.getCPtr(obj), SWIGTYPE_p_uint8_t.getCPtr(value));
  }

  public static SWIGTYPE_p_uint8_t uint8_tp_value(SWIGTYPE_p_uint8_t obj) {
    return new SWIGTYPE_p_uint8_t(brickpiJNI.uint8_tp_value(SWIGTYPE_p_uint8_t.getCPtr(obj)), true);
  }

}
