/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.brickpi3.java;

public class i2c_struct_t extends SWIG {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected i2c_struct_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(i2c_struct_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        brickpiJNI.delete_i2c_struct_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public boolean equals(Object obj) {
  boolean equal = false;
  if (obj instanceof i2c_struct_t)
    equal = (((i2c_struct_t)obj).swigCPtr == this.swigCPtr);
  return equal;
  }
  public int hashCode() {
    return (int)swigCPtr;
  }
  protected long getPointer() {
    return swigCPtr;
  }

  public void setSpeed(short value) {
    brickpiJNI.i2c_struct_t_speed_set(swigCPtr, this, value);
  }

  public short getSpeed() {
    return brickpiJNI.i2c_struct_t_speed_get(swigCPtr, this);
  }

  public void setDelay(short value) {
    brickpiJNI.i2c_struct_t_delay_set(swigCPtr, this, value);
  }

  public short getDelay() {
    return brickpiJNI.i2c_struct_t_delay_get(swigCPtr, this);
  }

  public void setAddress(short value) {
    brickpiJNI.i2c_struct_t_address_set(swigCPtr, this, value);
  }

  public short getAddress() {
    return brickpiJNI.i2c_struct_t_address_get(swigCPtr, this);
  }

  public void setLength_write(short value) {
    brickpiJNI.i2c_struct_t_length_write_set(swigCPtr, this, value);
  }

  public short getLength_write() {
    return brickpiJNI.i2c_struct_t_length_write_get(swigCPtr, this);
  }

  public void setBuffer_write(short[] value) {
    brickpiJNI.i2c_struct_t_buffer_write_set(swigCPtr, this, value);
  }

  public short[] getBuffer_write() {
    return brickpiJNI.i2c_struct_t_buffer_write_get(swigCPtr, this);
  }

  public void setLength_read(short value) {
    brickpiJNI.i2c_struct_t_length_read_set(swigCPtr, this, value);
  }

  public short getLength_read() {
    return brickpiJNI.i2c_struct_t_length_read_get(swigCPtr, this);
  }

  public void setBuffer_read(short[] value) {
    brickpiJNI.i2c_struct_t_buffer_read_set(swigCPtr, this, value);
  }

  public short[] getBuffer_read() {
    return brickpiJNI.i2c_struct_t_buffer_read_get(swigCPtr, this);
  }

  public i2c_struct_t() {
    this(brickpiJNI.new_i2c_struct_t(), true);
  }

}
