/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.brickpi3.java;

public final class SENSOR_STATE {
  public final static SENSOR_STATE SENSOR_STATE_VALID_DATA = new SENSOR_STATE("SENSOR_STATE_VALID_DATA");
  public final static SENSOR_STATE SENSOR_STATE_NOT_CONFIGURED = new SENSOR_STATE("SENSOR_STATE_NOT_CONFIGURED");
  public final static SENSOR_STATE SENSOR_STATE_CONFIGURING = new SENSOR_STATE("SENSOR_STATE_CONFIGURING");
  public final static SENSOR_STATE SENSOR_STATE_NO_DATA = new SENSOR_STATE("SENSOR_STATE_NO_DATA");
  public final static SENSOR_STATE SENSOR_STATE_I2C_ERROR = new SENSOR_STATE("SENSOR_STATE_I2C_ERROR");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static SENSOR_STATE swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + SENSOR_STATE.class + " with value " + swigValue);
  }

  private SENSOR_STATE(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private SENSOR_STATE(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private SENSOR_STATE(String swigName, SENSOR_STATE swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static SENSOR_STATE[] swigValues = { SENSOR_STATE_VALID_DATA, SENSOR_STATE_NOT_CONFIGURED, SENSOR_STATE_CONFIGURING, SENSOR_STATE_NO_DATA, SENSOR_STATE_I2C_ERROR };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

