/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.brickpi3.java;

public class sensor_infrared_t extends SWIG {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected sensor_infrared_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(sensor_infrared_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        brickpiJNI.delete_sensor_infrared_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public boolean equals(Object obj) {
  boolean equal = false;
  if (obj instanceof sensor_infrared_t)
    equal = (((sensor_infrared_t)obj).swigCPtr == this.swigCPtr);
  return equal;
  }
  public int hashCode() {
    return (int)swigCPtr;
  }
  protected long getPointer() {
    return swigCPtr;
  }

  public void setProximity(SWIGTYPE_p_uint8_t value) {
    brickpiJNI.sensor_infrared_t_proximity_set(swigCPtr, this, SWIGTYPE_p_uint8_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint8_t getProximity() {
    return new SWIGTYPE_p_uint8_t(brickpiJNI.sensor_infrared_t_proximity_get(swigCPtr, this), true);
  }

  public void setDistance(SWIGTYPE_p_int8_t value) {
    brickpiJNI.sensor_infrared_t_distance_set(swigCPtr, this, SWIGTYPE_p_int8_t.getCPtr(value));
  }

  public SWIGTYPE_p_int8_t getDistance() {
    long cPtr = brickpiJNI.sensor_infrared_t_distance_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int8_t(cPtr, false);
  }

  public void setHeading(SWIGTYPE_p_int8_t value) {
    brickpiJNI.sensor_infrared_t_heading_set(swigCPtr, this, SWIGTYPE_p_int8_t.getCPtr(value));
  }

  public SWIGTYPE_p_int8_t getHeading() {
    long cPtr = brickpiJNI.sensor_infrared_t_heading_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int8_t(cPtr, false);
  }

  public void setRemote(SWIGTYPE_p_uint8_t value) {
    brickpiJNI.sensor_infrared_t_remote_set(swigCPtr, this, SWIGTYPE_p_uint8_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint8_t getRemote() {
    long cPtr = brickpiJNI.sensor_infrared_t_remote_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_uint8_t(cPtr, false);
  }

  public sensor_infrared_t() {
    this(brickpiJNI.new_sensor_infrared_t(), true);
  }

}
